coderetreat/coderetreat.org

- _data/videos.yaml
- _includes/navigation.html
- style.scss
- videos.html
* Added videos page with the videos from the old site
* Changed styles to show each video with a shadow
* Change video list to be sorted by date
* Reviewed video list and left only the ones I believed are more relevant
Closes #3
> Added videos page with videos list from old site

- _data/events/istanbul.json
I have added an event for Istanbul
> add: event in istanbul

- _data/events/Malaga.json
@MalagaScala, MálagaJUG and TechTalentSouth Spain are organizing the first code retreat in Málaga ever!
> Add Málaga (Spain)

- _data/events/Munich.json
> added GDCR17 Munich Country

- _includes/navigation.html
Hi @rradczewski 
Sorry about that! Now the touch event should also work on phones. Let me know if you spot any issues!
> Fix touch event for mobile nav

- _data/events/Turku.json
I need to work with fellow hosts to define registration links, and such.
> adding Turku

- _data/events/Thessaloniki.json
> Add Thessaloniki GDCR event

- _data/events/SLC.json
Add event data for Salt Lake City, Ut.
> Add event data for SLC

- _includes/hero.html
For the sake of inclusive language. 
Context: https://gist.github.com/alastairs/f00d1b81bfacbaddb064ecb9748cfd94
> Replace craftsmanship with crafting @ home page

- events/event_schema.json
- test/events/cityIsEmpty.json
- test/events/countryIsEmpty.json
- test/events/titleIsEmpty.json
- test/events/urlIsEmpty.json
- test/validate_events.test.js
Validating that title, url, city and country have at least 1 character.
> Issue #72: Validating title, url, city, and country 

- _data/events/frankfurtAmMain.json
Changed the file as recommended.
> GDCR 17 in Frankfurt@itemis

- _data/events/Pittsburgh.json
Moderators will be updated in a future PR, went with hosting org for now.
> Adds Pittsburgh GDCR17

- _data/events/Denver.json
Hi!
Please register our Denver location!
Thanks!
Kim
> Adding Denver GDCR location

- Gemfile
- Gemfile.lock
- _plugins/sort_by_location.rb
- css/style.scss
- events/index.html
* Sorted events by country adding new custom filter
* Added map with events
* Added filter by country
Closes #26 #63
> Added location map, sorting by Country and filter by country to events

- _data/events/Pordenone.json
> Register event in Pordenone

- _data/events/osnabrueck.json
Already looking forward to a stunning event as every year!
> Added 'Osnabrueck' as event location.

- _data/events/Saskatoon.json
Register a new event for Saskatoon, Canada
> Register event in Saskatoon, Canada

- _data/events/Denver.json
Ohmygosh, will this PR to add moderators to Denver event work? :-)
> Add moderators to Denver event

- _data/events/Lodz.json
> Register event in Lodz,Poland

- pages/hosting/faq.md
> Remove date, rephrase in a more general way

- _data/events/Erlangen.json
Hi there, here's our registration for the city of Erlangen, Germany.
Thanks,
Tim B.
> Added event in Erlangen, Germany

- _data/events/Pittsburgh.json
> Adds facilitator to Pittsburgh event

- _data/events/Osaka.json
Add Osaka (Japan) Event.
Thank you.
>  Add GDCR in Osaka

- _data/events/Riga.json
Riga was added as a city where GDCR 2017 will take place.
> Adding Riga.

- _data/events/Columbus.json
Let me know if you have any questions or concerns.  Thanks!
> Adding the data for the Columbus, OH coderetreat.

- _data/events/Calgary.json
create event json for Calgary, please review
> create event json for Calgary

- pages/hosting/checklist.md
- pages/hosting/hosts.md
Checklist for hosts, guidance to remember what needs to be done for hosting.
Added text to hosts.md to link to checklist.md.
> Hosts checklist as guidance

- _data/trainings/trainings-2017.json
> Fix dead link to Eric's trainer photo

- _data/events/Lyon.json
> add the event for Lyon

- _data/events/Heilbronn.json
Added event information for GDCR17 in Heilbronn
> Heilbronn GDCR17

- _data/events/Hyderabad.json
Adding new city for CDCR17; Hyderabad, india
> Adding City Hyderabad, India

- _data/events/Logrono.json
- pages/training.md
> Add GDCR17 Logroño, SPAIN

- _data/events/Cambridge-UK.json
Add data for the event in Cambridge (UK)
> Add Cambridge, UK event

- _data/events/istanbul3.json
Istanbul Java User Group venue is added
> Istanbul Java User Group venue is added 

- _data/events/Bangkok.json
Register Bangkok Thailand for GDCR 2017
> Register Bangkok Thailand for GDCR 2017

- _data/events/London-ThoghtWorks.json
I would like to join to the next facilitator training.
> New Event for ThoughtWorks London

- _data/events/Beijing.json
> add event GDCR 2017 Beijing

- _data/events/EPAMHyderabad.json
Adding EPAM Hyderabad GCDR 17 event.
> Adding EPAM Hyderabad

- _data/events/Santiago.json
The Software Crafters Comunity is organizing a GDCR on Santiago, Chile
> Organizing GDCR 17 in Santiago, Chile

- _data/events/Barcelona-Wallapop.json
Thanks for your welcome! Yes, of course! I added the facilitators. Maybe we there are more people involved on that but at this particular moment, those are a guarantee.
> Added Wallapop Barcelona event - Awesome

- _data/events/Hamburg.json
Please add the GDCR17 of the software craftmanship chapter Hamburg, Germany: Softwerkskammer Hamburg.
The event page: https://www.meetup.com/de-DE/sokahh/events/239067827/
> add Hamburg,Germany to event list

- _data/events/Stockholm.json
Yey! 🎉🤓
This GDCR17 event will be hosted/sponsored by Citerus AB, but we are still looking for a co-host within the Stockholm meetup community. 🔎
Cheers!
@erorcodes  💻
> Added an event in Stockholm for GDCR17 

- _data/events/Budapest.json
"This year, registering your event at coderetreat.org is easier than it has ever been!" >> In what universe is this process easy? It couldn't be more complicated... The UX guy in me just died of a heart attack...
> Adding the Budapest event

- _data/events/Johannesburg.json
Added the event for Johannesburg, South Africa.
> Create Johannesburg.json file

- _data/events/Beijing-ThoughtWorks.json
Add the 2nd GDCR 2017 event in Beijing.
> add Beijing-ThoughtWorks.json

- _data/events/LasPalmasGC.json
Hello, I would like to register my headquarters for the GDCR, thanks
> add event in Las Palmas de Gran Canaria

- _data/events/Valencia.json
Register Valencia event for Nov 18th.
https://www.meetup.com/es-ES/Aprende-a-programar-en-Valencia/events/244747810/
> Register Valencia - Spain event

- _data/events/Asturias.json
Asturias joins the party! ;) 🎉  🎉  
More info @ https://www.eventbrite.com/e/asturias-global-day-of-code-retreat-2017-tickets-39731055657
> Add event in Asturias, Spain

- _data/events/Nagoya.json
Add Nagoya/Japan event! Thanks!
> Add GDCR17 event in Nagoya (Japan)

- _data/events_gdcr2018/Malaga.json
After a fantastic first GDCR in 2017, Málaga wants more!
Thanks!
> Add Málaga, Spain to GDCR18

- _data/events_gdcr2018/Melbourne.json
Added the #GDCR for Melbourne, Australia
> registering gdcr18 event in Melbourne, Australia

- _data/events_gdcr2018/TelAviv.json
> Added an event in Tel Aviv!

- _data/events_gdcr2018/ColumbusOH.json
Register GDCR18 in Columbus, OH, USA
> Add GDCR18 in Columbus OH

- _data/events_gdcr2018/Pune-Nelkinda.json
- _data/events_gdcr2018/Pune-SimplyTech.json
- _data/events_gdcr2018/Pune-TechnoWise.json
- _data/events_gdcr2018/Pune-e-Zest.json
Added the Pune coderetreats organized by Nelkinda for the Global Day of Coderetreat 2018.
* e-Zest
* Nelkinda
* Perennial Systems / SimplyTech Meetup
* Technogise / TechnoWise Meetup
> Add Pune coderetreats organized by Nelkinda.

- _data/events_gdcr2018/WestlakeVillage.json
Adding CJ Engineering twitter to sponsors list.
> Added cj engineering sponsor to Westlake Village 2018 meetup

- _data/events_gdcr2018/Cambridge.json
Details like moderators are still to be confirmed, but the event is live on Meetup and accepting RSVPs!
> Add Cambridge UK GDCR date

- _data/events_gdcr2018/Duesseldorf.json
> Added event in Duesseldorf / Germany

- _data/events_gdcr2018/Pune-TechnoWise.json
> Add TechnoWise moderators.

- _data/events/Vechta.json
- _data/events_gdcr2018/Vechta.json
Add GDCR18 in Vechta/Germany to the list of events.
> Add GDCR18 in Vechta

- _data/events_gdcr2018/Seattle-8thLight.json
Added new GDCR in Lynnwood Washington
> Add 8th Light Seattle GDCR

- _data/events_gdcr2018/Asturias.json
> Add Asturias GDCR 2018 event

- _includes/countdown.liquid
> Remove date filter and default value in countdown

- _data/events_gdcr2018/Lille.json
Thanks for this site and event :)
> Adding GDCR'18 at Epitech in Lille

- _data/events_gdcr2018/Dublin.json
This year we want to organize the GDCR in Dublin for the first time so I added the location.
> Add Dublin location

- _includes/event-map.html
- _sass/base.scss
- _sass/landing/hero.scss
Superseeds/Closes #344 
See #344 and #336 for the context. We all can push to this branch :tada:
> Issue 336 add sort of intro at homepage

- _data/events_gdcr2018/washingtondc.json
Global Day of Code Retreat for Washington DC
> Adding Washington DC to the GDCR 2018

- _data/events_gdcr2018/LosAngeles.json
- package-lock.json
Add Downtown Los Angeles GDCR 2018 event.
> Add Downtown Los Angeles GDCR 2018 event.

- _data/events_gdcr2018/Mumbai.json
For GDCR-18 at Media.net, Mumbai, India
> Adding event in Mumbai at media.net 

- _data/events_gdcr2018/London-Codurance.json
Code retreat at Codurance offices.
> Added london codurance 2018

- _data/events_gdcr2018/Istanbul.json
Added event information for GDCR18 in Istanbul.
> Istanbul GDCR18

- _data/events_gdcr2018/madrid.json
Fix Keyvan handle and add sponsor
> fix-madrid

- _data/events_gdcr2018/Zaragoza.json
Added GDCR18 for Zaragoza/Spain
> Added GDCR18 for Zaragoza/Spain

- _data/events_gdcr2018/Valencia.json
Register Valencia code retreat 2018
> Register Valencia retreat

- _data/events_gdcr2018/Mumbai-Media.net.json
Renamed file to allow for other events in Mumbai and added sponsor name.
> [ Mumbai GDCR18 ] Renamed file and added sponsors

- events/event_schema.json
- events/index.html
- js/map.js
Instead of providing the location details, just use `"location": "virtual"` like so:
```json
{
"title": "GDCR18 on Twitch",
"url": "https://www.twitch.tv/YaddaYadda",
"moderators": [],
"location": "virtual"
}
```
> Allow virtual events and list them under 'Find an event'

- _data/events_gdcr2018/Columbus.json
GCDR event in Columbus OH for TDD on November 17
> GCDR event in Columbus for TDD on November 17

- _data/events_gdcr2018/Pamplona.json
Adds a GDCR event in Pamplona. 
It will be hosted and sponsored by @Openbravo.
> Add GDCR in Pamplona

- _data/events_gdcr2018/washingtondc.json
> Add sponsor to Washington DC entry

- _data/events_gdcr2018/Bucharest-craftsmanship.json
Facilitated by Victor Rentea (victorrentea.ro) and fellow craftspersons.
> add Bucharest-craftsmanship CodeRetreat

- _data/events_gdcr2018/Cambridge.json
We now have names, whoop. Let's do this :)
> Add moderators/sponsor for Cambridge, UK

- _data/events_gdcr2018/London-GDS.json
This year GDS is hosting a GDCR on 17 of November.
> Added event for London-GDS

- _data/events_gdcr2018/Kalispell.json
I followed the steps on the register event page found here: https://www.coderetreat.org/register-event/
> Add Kalispell, MT event location for GDCR2018

- _data/events_gdcr2018/Portland_AgilePDX.json
Creating Portland_AgilePDX.json file for a second portland-based coderetreat event.
> Create new Portland_AgilePDX.json

- _includes/navigation.html
- _sass/base.scss
- pages/about.html
- Added quote style for Corey's message to about page
- Changed order of articles in top navigation
> Added quoted style for Corey's message on about page

- _data/events_gdcr2019/montreal.json
> Add Montréal for GDCR19

- _data/events_gdcr2019/zurich.json
> added Zurich

- _data/events_gdcr2019/Seattle-GlobalCDK.json
Adding in a new json file for the Seattle GDCR2019
> Adding in notice for the Seattle-GlobalCDK GDCR2019

- _data/events_gdcr2019/wuerzburg.json
Hello,
I added the event-file for the gdcr2019
Greetings,
Dominik
> gdcr2019 in wuerzburg

- _data/events_gdcr2019/singapore.json
Hi,
Adding Singapore to the list. JuniorDevSG will be helping to organize this.
Many thanks!
> Add Singapore 2019 to the list.

- _data/events_gdcr2019/edinburgh.json
Please add the Edinburgh event.
> Added the Edinburgh json file

- _data/events_gdcr2019/vienna-friday.json
Hello!
I've created the entry for Friday in Vienna, Austria - we managed to get a second location as well to cover both dates.
> added Vienna, Austria - Friday entry

- _data/events_gdcr2019/bratislava.json
Hi, we are about to organize Coderetreat in Bratislava. We have in-house experience with Coderetreat, but this time we would like to address also the general public.
> Added Global Day Of Coderetreat 2019 Bratislava Event

- _data/events_gdcr2019/shizuoka.json
Please add Shizuoka, Japan event.
> Add Shizuoka, Japan

- _data/events_gdcr2019/lucerne.json
Added details GDCR 2019  in Lucerne
> GDCR 2019 Lucerne

- _data/events_gdcr2019/spain-remote.json
Added a remote event, for 2019, managed from Spain.
> Added one remote GDCR from Spain

- _data/events_gdcr2019/tes-remote.json
Hello!
We're hosting a fully remote event :)
> Add remote event sponsored by Tes

- _data/events_gdcr2019/annarbor.json
> Ann Arbor title update

- _data/events_gdcr2019/bordesholm.json
- _data/events_gdcr2019/kagawa.json
Created the file bordesholm.json in order to add an event
> Created bordesholm.json in order to add an event

- _data/events_gdcr2019/las_palmas.json
Sorry for the delay.  
I added las palmas into list the events
> add las palmas de gran canaria to list of events

- _data/events_gdcr2019/metro_manila.json
Hi, submitting a registration for a GDCR event we're having at Manila, PH.
> GDCR 2019 - Manila, PH

- _data/events_gdcr2019/melbourne.json
> Add GDCR Melbourne (Australia) 2019

- _data/events_gdcr2019/rennes.json
Takes place on Friday, November 15th.
Event link: https://www.meetup.com/fr-FR/Software-Craftsmanship-Rennes/events/265085915/
> GDCR 2019 in Rennes (France)

- _data/events_gdcr2019/berlin-klarna.json
- _data/events_gdcr2019/stockholm-klarna.json
> GDCR Klarna Berlin and Stockholm

- _data/events_gdcr2019/PortlandWomenOrUsa.json
Add event file for GDCR 2019 Portland women-focused event
> Please add Portland, Oregon women-focused event

- _data/events_gdcr2019/columbus-oh.json
Event registration information for GDCR 2019 at The Forge by Pillar in Columbus, OH, USA. Thanks!
> Add Columbus OH GDCR 2019 registration

- _data/events_gdcr2019/villeneuve-d-ascq.json
Hi,
I organise an event for GDCR 2019 in Villeneuve d'Ascq (France) on Friday November 15th.
Thanks !
> Add event file for GDCR 2019 @ Villeneuve d'Ascq (France)

- _data/events_gdcr2019/san_diego.json
In this PR
=============
* adds the san_diego.json registration for 2019
Discussion
============
Stoooooooooooked!!!!!!!
> adds san diego

- events/index.html
The country filter dropdown is now URL sharable, on the events page.
> URL sharable country on events page

- _data/events_gdcr2019/berlin-hexad.json
- _data/events_gdcr2019/berlin-vw.json
- _data/events_gdcr2019/wolfsburg.json
Forgot to add additional sponsor information for all the 3 events hosted by Hexad and VW
> Update sponsor information for Hexad and VW events

- _data/events_gdcr2019/pune.json
Hello,
I've added the facilitators for the Coderetreat at Equal Experts.
Please do tweet the event from code retreat account as you had told in the previous raised PR.
Thanks
> Update: Add facilitators for Equal Experts, Pune

- _data/events_gdcr2019/Milan-miaplatform.json
> Add Mia-Platform Milan Event

- _data/events_gdcr2019/toulouse-friday.json
Adding Friday session for Toulouse in France.
> Adding GDCR2019 - Toulouse Friday events

- _data/events_gdcr2019/Paris.json
Arolla will facilitate the GDCR this year in Paris :)
> Add GDCR19 event in Paris, France

- _data/events_gdcr2019/Gdansk.json
> Adding event in Poland.Gdansk - Epam office

- _data/events_gdcr2019/pardubice.json
Wrong city in a title. ❤️copy&paste
> Fix GDCR in Pardubice

- _data/articles/experiences/as-a-facilitator/2019-Vineet-Kulkarni.yaml
Committer: Vineet Kulkarni<vineetsk@gmail.com>
> Added 2019 Pune coderetreat

- _data/articles/experiences/as-an-attendee/2019-Krystian-Adamski.yaml
https://adamski.pro/tdd/2019/11/19/coderetreat.html - Coderetreat - dlaczego warto tam być
> adamski.pro - coderetreat article as attendee

- _data/articles/experiences/as-a-facilitator/2019-Ruddy-Riba.yaml
Hello!
Here's a write up by @RuddyN of our experience hosting a remote event. Hope it's useful! Let me know if you need me to add anything else or if this is ok... 
Thank you 😄
> Adding post about remote GDCR hosted at Tes

- _data/articles/experiences/as-a-facilitator/2019-Paul-Sobocinski.yaml
Hi all :wave:
We hosted GDCR Toronto last year at Connected. I wrote up an article based on my experience and in particular, the impression it made on me. I had attended GDCR twice before, and this was my first time hosting, organizing, and facilitating. I hope you enjoy the article and are able to add it to the website. :smile:
Also, a special shout-out to @amckinnell, @bradrobertson, @chrisgow, and Shan Syed for facilitating, and to @makrandgupta for co-organizing. :rocket:
Link to article: https://www.connected.io/post/four-reasons-why-software-engineering-needs-more-coderetreats/
> Add experience-as-a-facilitator 2019 Toronto

- _data/articles/about-the-format/2019-Peter-Kofler.yaml
- pages/training.md
Hi, I added two links to the podcast, which is like a training session just shorter and focused on three questions that have been asked in previous year's trainings. Hope this helps new facilitators.
> Links to Coderetreat Facilitation Podcast

- _data/events/japan-akihabara-tokyo-2020-11-07-global-day-of-coderetreat-2020-in-tddyyx.json
We will hold GDCR2020 in Akihabara, Japan. Please add our event.
> add GDCR2020 in Akihabara, Japan

- _data/events/virtual-2020-11-07-global-day-of-coderetreat-2020-manila.json
Hi, Submitting a pull request for a half-day Coderetreat we're holding in Manila.
> Added GDCR event for Manila

- _data/events/virtual-2020-11-07-asturias-global-day-of-coderetreat-2020.json
> Add Asturias

- _data/events/virtual-2020-11-06-global-code-retreat-with-remote-hack.json
Hello!
We'd love to be part of the Global Code Retreat ❤️ 🗺️
> Remote Hack ☎️

- _data/events/virtual-2020-11-06-global-day-of-coderetreat-singapore-2020.json
On 7th November. Virtual event.
> Add event for GDCR Singapore 2020

- _data/events/virtual-2020-11-07-global-day-of-coderetreat-2020-equalexperts-pune-remote.json
Adding Equal Experts as host to #GDCR2020  from Pune, India
> add equal experts as host to the #GDCR 2020 list.

- _data/events/virtual-2020-11-06-caos-mob-programming-global-day-of-coderetreat.json
- _data/events/virtual-2021-11-06-caos-mob-programming-global-day-of-coderetreat.json
A free,  day-long, intensive practice event, focusing on the fundamentals of software development and design, explored through Mob Programming.
> 2021 - CAOS Mob Programming: Global Day Of Coderetreat

- _data/events/virtual-2021-11-06-jug-istanbul-global-day-of-coderetreat-2021.json
Hello, we are JUG Istanbul, you can find our event JSON file in the related directory.
> adds jug istanbul event json

- _data/events/virtual-2021-11-06-jug-istanbul-global-day-of-coderetreat-2021.json
Hello, we updated our event date to be able to execute it on the coderetreat event days.
> Updates dates according to the coderetreat date

- _data/events/virtual-2021-11-06-jug-istanbul-global-day-of-coderetreat-2021.json
Updates JUG Coderetreat date to the one day after
> Updates JUG Coderetreat date to the one day after

- _data/events/spain-barcelona-2021-11-13-global-day-coderetreat-2021-codurance-spain.json
We're hosting the event this year at Codurance, Barcelona. We intend to make a physical event, so Covid-measures will be taken, like an antigens test for those attending.
Thanks for approving this PR
> Creating Barcelona @Codurance event

- _data/events/south-africa-cape-town-2021-11-12-gdcr-cape-town-remote.json
Better late than never ;) adding the Cape Town event, for stats and history.
> Add Cape Town GDCR21 event

- _data/events/united-states-pittsburgh-2021-11-12-global-day-of-code-retreat-pittsburgh.json
> Add Pittsburgh Code Retreat Event

- _data/events/virtual-2022-03-19-softwerkskammer-vienna.json
Small codetreat from SWK-vienna on 19.3.2022
> another coderetreat from swk vienna

- _data/events/virtual-2022-07-05-sportradar-brutal-coderetreat.json
> Add next CR in Vienna

- _data/events/turkey-istanbul-2022-11-05-global-day-of-coderetreat-jugistanbul.json
I followed the steps and added the Coderetreat event of JUG-Istanbul. Please inform if any missing information.
> adds jug istanbul coderetreat event json file to the eventes

- _data/events/spain-barcelona-2022-11-05-global-day-coderetreat-2022-codurance-spain.json
- _data/events/spain-madrid-2022-11-05-global-day-coderetreat-2022-codurance-spain.json
We're hosting the event this year at our Codurance offices, in Barcelona and Madrid.
Thanks for approving this PR :)
> Adds Barcelona event @Codurance

- _data/events/poland-wroclaw-2022-11-05.json
klose brothers PL is joining GDCR 2022
> Add GDCR 2022 Wroclaw, PL 

- _data/events/germany-leipzig-2022-11-04-global-day-of-code-retreat-2022-in-leipzig-codecentric-ag.json
> fixed date, was wrong  before

- _data/events/virtual-2022-11-04-global-day-of-code-retreat-nagarro-colombo-2022.json
Add moderators  code retreat Colombo event
> 1. Moderators addition code retreat Colombo event

- _data/events/virtual-2022-11-04-global-day-of-code-retreat-nagarro-colombo-2022.json
Date correction of the colombo code retreat
> Date correction of the colombo code retreat

- _data/events/romania-bucharest-2022-11-11.json
Long time, no see :)
Cheers from an old friend!
> Add coderetreat @ Codiax 2022 in Bucharest, Romania

- _data/events/italy-milano-2022-11-05-global-day-of-coderetreat-2022.json
The end date must be after the start date
> fix: milano event end date

- _data/news.yaml
Hi!
This year we have hosted GDCR in Wrocław @ Ocado Technology. I did a little writeup of my experiences and wanted to share it here :wink:
> Add an article on GDCR event in Wrocław

- _data/news.yaml
I missed the more important link before, this should fix all occurences.
> Fix second broken link to Toronto GDCR-Article

- _data/events/chicago-2023-thoughtworks.json
Adding description of Chicago event, hosted by Thoughtworks
> adds article for Chicago event hosted by Thoughtworks

- _data/events/poland-wroclaw-2023-11-04-global-day-of-coderetreat.json
> added gdcr Wroclaw, Poland :

- _data/events/germany-nuremberg-2023-11-04.json
we're looking forward joyning the world wide GDCR community again!
> adding GDCR event in Nuremberg/Germany on 2023-11-04

- _data/events/germany-stuttgart-2023-03-11-breuninger.json
Commits can/should be squashed on merge ;)
> Add Stuttgart-Event to 2023 Global Day of Coderetreat

- _data/events/2023-11-04-japan-akasaka-global-day-of-coderetreat-2023-in-tddyyx.json
Please add our GDCR 2023 event in Akasaka, Japan.
> Add GDCR 2023 in Akasaka, Japan

- _data/events/2023-11-03-united-states-des-moines-global-day-of-coderetreat-des-moines.json
- _data/events/2023-11-03-united-states-san-antonio-global-day-of-coderetreat-san-antonio.json
Adding global day of coderetreat events for:
- Des Moines
- San Antonio
November 3rd, 2023 - 8:30 AM to 5 PM
> Adds des-moines and san-antonio events

- _data/events/2023-11-04-poland-poznan-global-day-of-coderetreat-z-jug-poznan-oraz-allegro-tech.json
> Global Day of Coderetreat with JUG Poznań and Allegro Tech 2023-11-04

- facilitators/resources.md
I exchanged the link from my bird site profile to my mastadon profile
> exchange bird site link with mastadon link to mrksdck profile

- _data/events/2023-11-04-new-zealand-auckland-global-day-of-coderetreat-2023-auckland-nz.json
> Added Auckland, NZ

- _data/events/2023-11-25-mexico-manzanillo-global-day-of-code-retreat-manzanillo.json
Added Manzanillo, Colima event. 
[Playas on Tech Community](https://playasontech.com/)
> [add event] gdcr in Manzanillo Colima

- .gitignore
- _data/events/2024-11-09-switzerland-bern-global-day-of-coderetreat-2024-bern-switzerland.json
- _data/events/2024-11-09-switzerland-zurich-global-day-of-coderetreat-2024-zurich-switzerland.json
- _data/events/switzerland-zurich-2024-11-09-global-day-of-coderetreat-2024-switzerland.json
We have expanded, now Bern is also being moderated.
> Swiss contribution - Zuerich and Bern

- _data/events/2024-11-08-austria-salzburg-coderetreat.json
Adds GDCR in Salzburg '24
https://www.meetup.com/de-DE/salzburg-software-craftsmanship/events/303239765/
> Add salzburg GDCR 2024 to event listing

- _data/events/2024-11-08-denmark-copenhagen-global-day-of-coderetreat-friday.json
- _data/events/2024-11-09-denmark-copenhagen-global-day-of-coderetreat-saturday.json
Add GDCR events for Friday and Saturday in Copenhagen
> Add Copenhagen GDCR 2024 events to event listing

- _data/events/2024-11-09-germany-karlsruhe-global-day-of-code-retreat-karlsruhe-germany.json
> Adding Karlsruhe/Germany

- _data/events/2024-11-09-united-states-iowa-des-moines-dsm.json
- _data/events/2024-11-09-united-states-minnesota-twin-cities-msp.json
- _data/events/2024-11-09-united-states-texas-san-antonio.json
- Des Moines Iowa, 
- Twin Cities Minnesota
- San Antonio Texas
> Adds US events for IA, MN, and TX

- _data/events/2024-11-09-germany-koln-gdcr-swk-cologne.json
publish cologne event of gdcr 2024
> Publish 2024-11-09-germany-koln-gdcr-swk-cologne.json

- _data/events/2024-11-16-emea-online-global-day-of-coderetreat-with-tech-risers-women.json
Addition of virtual half day event, hosted by Tech Risers Women - open to everyone
> Tech Risers Women 2024 event

- _data/events/2024-11-09-france-lyon-global-day-of-code-retreat-lyon-2024.json
> Fix session Lyon

- _data/communities/india-pune-devday-pune.json
- _data/events/2024-11-09-india-pune-global-day-of-coderetreat-2024-devday-pune.json
- added new event to register for the coderetreat 2024
- corrected the location of the devday pune community
> Add event - Global Day of Coderetreat 2024 @DevDay Pune India

- _data/events/2024-11-09-united-states-pittsburgh-global-day-of-coderetreat-pittsburgh.json
Adds sponsors, drops a moderator
> Updates Pittsburgh 2024 GDCR event

- _data/events/2024-11-09-france-paris-global-day-of-code-retreat-paris.json
> fix date of paris code retreat

- _data/events/2024-11-23-japan-okinawa-coderetreat-okinawa-2024-in-tddyyx.json
We will hold Coderetreat in Okinawa, Japan. 
Please add our event.
> add Coderetreat Okinawa 2024 in #tddyyχ in Okinawa, Japan
