_data/events/istanbul2.json

We would like to register a second event for GDCR17 to Istanbul.

added second event for Istanbul, Turkey

---

_includes/navigation.html
_sass/navigation.scss

Hi @rradczewski !
I saw that you created an issue for mobile nav styling, so I took the liberty to improve it a bit. Have a look and see what you think. I followed the example from the Bootstrap website, as you suggested.
I'm not using iPad or phone sizes for my media queries but just pixel sizes, related to the design. So when I thought it looked a bit crowded, I created a media query and changed the design a bit. 
It's not perfect, but I guess it addresses the main issue of the nav links coming out of the top bar.
Let me know what you think!
Rabea

Navigation styling for all screen sizes

---

_data/events/Morgantown.json

This commit adds event information for an event at the realtor.com offices in Morgantown, WV. It's been a few years since I ran an event in the area, and I'm looking forward to doing it again! Thanks!

Add event data for Morgantown

---

events/index.html

Now joining facilitator names on the events page with `, `.
Here's what it looks like now, one row with regular names, one with handles:
Thanks!

Issue #62: separate facilitator names with comma in event list.

---

test/invalid_events/coordinatesUnexpectedKey.json
test/invalid_events/locationUnexpectedKey.json
test/invalid_events/topLevelUnexpectedKey.json
test/validate_events.test.js

This tests `additionalAttributes` at all three levels the schema currently disallows them.

Add tests to disallow additionalAttributes

---

_data/events/London-Spektrix.json

Added the London event, based off Fleet Street in central London at the Spektrix London Offices.

Added the London Spektrix event

---

pages/training.md

When visiting the trainings page, users are forced to scroll down in order to find the next upcoming training session. 
Probably sorting them chronologically (what this change does) is a more convenient way to present the info to the users.
Before:
After:
Note: Dead link to Eric's pic has been already handled @ #150.

Show upcoming trainings chronologically

---

_includes/hosting.html

- Assuming: `/pages/hosting/hosts` was the intended target.
- Notice: _Diff_ also handles two minor formatting issues present in the file.

Fix dead link to 'Hosts' page

---

_data/events/Melbourne.json

Thoughtworks would like to host a code retreat in Melbourne.

Add GDCR 2017 Melbourne hosted by Thoughtworks

---

README.md

The description was not fully clear; after "Submit a pull request:" there was info on how to run the tests locally, giving the impression those commands would open a pull request. I think it is clearer now, please do confirm 😄
Cheers!
@erorcodes

Clarify the steps for registering an event on coderetreat.org

---

_data/events/Cambridge.json

It was set as "United States" but it seems that the other US events are "United States of America". This was causing both to show up in the drop-down.

Update Cambridge to group with other USA cities

---

_data/events/SophiaAntipolis.json

Hi, 
like last year, we plan to host the GDCR in our campus, a joint effort between the local software craftmanship community and the University of Nice.

Registering Sophia Antipolis for GDCR'17

---

_data/events_gdcr2018/Gdansk.json
_data/events_gdcr2018/Rzeszow.json

Adding two events in Rzeszow and Gdansk (Poland) organised by PGS Software company.

Added Rzeszow and Gdansk GDCR 2018 events in Poland 

---

_data/events_gdcr2018/London.json

London entry for GDCR 2018 hosted at the J.P. Morgan offices

Add GDCR2018 London entry

---

hosts/embedded.html
hosts/hosts.js

- Change hashtag from #gdcr17 to #gdcr18
- Switch to meet.jit.si for video calls
meet.jit.si will potentially support up to 50 participants (neeeever tried that and I'm skeptical given that the WiFi at the events will be highly under load already), but I'm considering to lower the amount of rooms per timezone cluster too :thinking: but that's a detail we can see to.
Most importantly, this PR restores videocall functionality. :+1:

Update hosting tools for #gdcr18

---

_data/events_gdcr2018/Malaga.json

Hats off to [The Workshop](https://theworkshop.com), who is providing venue, food and even childcare :-)

Add sponsor for Málaga code retreat

---

LICENSE
_includes/twitter-news.html

I'm starting to familiarize myself with the codebase a bit. I found 2 super mini changes that might be useful re license copyright date that was fairly outdated, as well as the twitter card in news.
Even though this change can be automatically merged, I wanted to create a pull request to check what our process is for changes anyway. 
Please advise :)

Updated copyright year in license from 2017 to 2019 & Added more recent twitter card to news.

---

_includes/event-map.html

As per [Trello Card](https://trello.com/c/O7aiGTQ0/54-explain-the-two-dates-asap), I added an explicit explanation right next to the date.
If this is alright for everyone, I'd merge it and also tweet a similar message so everyone knows what's going on

Add message to the organizers explaining why we have two dates this year

---

_data/events_gdcr2019/rheine.json

I would like you to list my GDCR event in Rheine on your site. I have created a proper rheine.json file in the directory according to your guidelines.

Create GDCR event in Rheine: add rheine.json

---

_data/events_gdcr2019/cologne-thoughtworks.json

Global Day of Code Retreat 2019 in the Cologne event. Sponsored by ThoughtWorks. Please approve it.

Add event file for GDCR 2019 Cologne @ThoughtWorks

---

_data/events_gdcr2019/gothenburg-fri.json

Global Day of Code Retreat Gothenburg 2019 hosted by ProAgile. I added a json file for this event.

added Gothenburg, Sweden

---

_data/events_gdcr2019/madrid.json

New GDCR19 event in Madrid sponsored by Spotahome 🚀

Add Madrid event @ Spotahome for GDCR19

---

_data/events_gdcr2019/berlin-vw.json

Add event for GDCR Berlin, hosted by Volkswagen Digital:Lab in partnership with Hexad GmbH

Add Volkswagen Digital:Lab Berlin

---

_data/events_gdcr2019/berlin-hexad.json

Add event for GDCR Berlin, hosted by Hexad Gmbh in partnership with Volkswagen Digital:Lab

Add Hexad Berlin

---

hosts/gdcr-tools/embedded.html
pages/facilitating/media-pack.md

Channel was '#gdrc' changed to '#gdcr'

fix typo in slack channel name

---

_data/articles/experiences/as-a-facilitator/2019-Terence-Duong.yaml

Hello Coderetreaters,
I'm looking to add my article for GDCR Melbourne 2019 into the list of blog entries.
[Find the blog post here!](https://medium.com/seek-blog/global-day-of-coderetreat-melbourne-2019-67f300937c9d)
I was wondering if it would be okay to add the blog entry to both, as guests would only check facilitation or attendee and this entry kind of includes both?
Regards,
Terence.

Add experience-as-facilitator 2019 Melbourne

---

_data/events/japan-shinagawa-tokyo-2020-11-07-global-day-of-coderetreat-2021.json

GDCR2021 in Shinjuku, Tokyo. Please add our event.

Add Global Day of Coderetreat 2021 - Shinjuku Tokyo

---

_data/events/london-2022-global-day-code-retreat-at-lscc.json

We're hosting a Global Day of Code Retreat at the London Software Craftsmanship Community on the 5th November, in London. I hope that we can add it to the official events page.

Add Global Day of Code Retreat session, London

---

_data/events/london-2022-global-day-code-retreat-at-lscc.json

Jetbrains have kindly offered to be an additional sponsor :smile:

Add Jetbrains as sponsor for London GDCR @ LSCC

---

_data/news.yaml

Here's my write-up about hosting GDCR this year in Toronto. Specifically, it focuses on the planning aspect; hopefully there will be a follow-up which will describe the day of the event and the learnings gained!
A special kudos to all the facilitators who made it happen: @murphykieran @erithmetic @deniseyu @spike01 @amckinnell thank you all, it wouldn't have been possible without your help.

Add an article on GDCR event in Toronto

---

_data/events/spain-barcelona-2023-11-04-global-day-coderetreat-2023-codurance.json
_data/events/spain-madrid-2023-11-04-global-day-coderetreat-2023-codurance-spain.json

We're hosting the event this year at our Codurance offices, in Barcelona and Madrid.
Thanks for approving this PR :)

Adds Barcelona and Madrid event @Codurance 2023

---

_data/events/2023-11-11-russia-moscow-moscow-coderetreat.json

We have celebration day in Russia on Nov, 4th, so we'll have long weekend. Many developerms will not be able to participate in the retreat.
We have thought about it and decided to move the retreat a week later. So, our retreat will take place on Nov, 11th.

Append Moscow retreat on Nov, 11

---

_data/events/2024-11-09-canada-toronto-global-day-of-coderetreat-toronto.json

Adding event for Global Day of Coderetreat Toronto for this year (2024).
Let's do this @msvivianso ! 🙌 🚀

Add event: Global Day of Coderetreat Toronto (2024)

---

_data/events/2024-11-09-united-states-chicago-global-day-of-coderetreat-chicago.json

Confirmed via the event signup page that it is actually happening on Saturday, not Friday as is indicated in the JSON.
@murphykieran heads up!

Fix event: typo in Chicago GDCR 2024

---

_data/events/2024-11-09-cambridge-global-day-of-code-retreat.json

Add event for November 9th 2024 in Cambridge, UK

Add Cambridge Global Day of Code Retreat
